# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Google App Engine

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'GCloud'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Set environment secrets
        uses: golang-enthusiast/app-yaml-env-compiler@v1.0
        env:
          ENV_CLIENT_ID: ${{ secrets.ENV_CLIENT_ID }}
          ENV_CLIENT_SECRET: ${{ secrets.ENV_CLIENT_SECRET }}
          ENV_PORT: ${{ secrets.ENV_PORT }}
          ENV_FIREBASE_KEY_ID: ${{ secrets.ENV_FIREBASE_KEY_ID }}
          ENV_FIREBASE_KEY: ${{ secrets.ENV_FIREBASE_KEY }}
          ENV_FIREBASE_EMAIL: ${{ secrets.ENV_FIREBASE_EMAIL }}
          ENV_FIREBASE_CLIENT_ID: ${{ secrets.ENV_FIREBASE_CLIENT_ID }}
          ENV_FIREBASE_CERT_URL: ${{ secrets.ENV_FIREBASE_CERT_URL }}

      - name: 'Deploy to Google Cloud'
        id: deploy-to-webapp
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.gcp_credentials }}
